### ISSUE TITLE
is this project still active?

### ISSUE THREAD

**Issue by Trolldemorted** [langboost/libtextsecure-uwp#3]
title says it all, i think.

Will you incorporate the recent changes, and features like running as a slave device like [this fork](https://github.com/Turasa/libsignal-service-java)?

**Comment by jeff-r-skillrev** [comment]
Yep. For example: https://github.com/golf1052/libsignalservice-uwp

**Comment by Trolldemorted** [comment]
thanks for the quick reply!

will you merge the commits? is the nuget package based on your repository or on golf1052's fork?

**Comment by jeff-r-skillrev** [comment]
Yes, that's my normal process when I receive pull requests. Currently, the last package was published about a year ago.
